from yacs.config import CfgNode as CN

cfg = CN()

# cfg.DATASET = 'MovieGraphs-Short'
# cfg.DATASET = 'LVU'
cfg.DATASET = 'ViSR'
# cfg.DATASET = 'HLVU'
# cfg.MODEL_NAME = 'GCAT'
cfg.MODEL_NAME = 'GCAT-CT'

cfg.DATA = CN()
cfg.DATA.SPLIT_FILE_PATH = ''
cfg.DATA.MOVIE_SPLIT_FILE_PATH = ''
cfg.DATA.NO_MOVIE_OVERLAP_SPLIT_FILE_PATH = ''
cfg.DATA.SHUFFLE_NO_MOVIE_OVERLAP_SPLIT_FILE_PATH = ''
cfg.DATA.EXCLUDE_LIST = ['']
cfg.DATA.LABEL_DIR = ''
cfg.DATA.LVU_SPLIT = ''
cfg.DATA.LVU_LABEL = ''
cfg.DATA.VISR_SPLIT_PATH = ''
cfg.DATA.VISR_LABEL = ''
cfg.DATA.VISR_FRAME_DIR = ''
cfg.DATA.HLVU_SPLIT_PATH = ''
cfg.DATA.HLVU_LABEL_DIR = ''
cfg.DATA.HLVU_FRAME_DIR = ''


cfg.TRAIN = CN()
cfg.TRAIN.BATCH_SIZE = 
cfg.TRAIN.NUM_WORKERS = 
cfg.TRAIN.EPOCHS = 
cfg.TRAIN.LR = 
cfg.TRAIN.WEIGHT_DECAY = 

cfg.FEATURE = CN()
cfg.FEATURE.BERT_FEATURE_DIR = ''
cfg.FEATURE.BACKRGOUND_FEATURE_Path = ''
cfg.FEATURE.FACE_FEATURE_DIR = ''

# # LVU
# cfg.FEATURE.FACE_FEATURE_DIM = 
# cfg.FEATURE.TEXT_DIM = 
# cfg.FEATURE.BACKGROUND_DIM = 
# cfg.FEATURE.GRAPH_FEATURE_DIM = 
# ViSR
cfg.FEATURE.FACE_FEATURE_DIM = 
cfg.FEATURE.TEXT_DIM = 
cfg.FEATURE.BACKGROUND_DIM = 
cfg.FEATURE.GRAPH_FEATURE_DIM =  # equal to face_dim
# # HLVU
# cfg.FEATURE.FACE_FEATURE_DIM = 
# cfg.FEATURE.TEXT_DIM = 
# cfg.FEATURE.BACKGROUND_DIM = 
# cfg.FEATURE.GRAPH_FEATURE_DIM = 

# cfg.FEATURE.LVU_BERT_FEATURE_DIR = ''
cfg.FEATURE.LVU_BACKRGOUND_FEATURE_Path = ''
cfg.FEATURE.LVU_FACE_FEATURE_DIR = ''
cfg.FEATURE.VISR_BERT_FEATURE_DIR = ''
cfg.FEATURE.VISR_BACKRGOUND_FEATURE_DIR = ''
cfg.FEATURE.VISR_FACE_FEATURE_DIR = ''
cfg.FEATURE.HLVU_BERT_FEATURE_PATH = ''
cfg.FEATURE.HLVU_BACKRGOUND_FEATURE_DIR = ''
cfg.FEATURE.HLVU_FACE_FEATURE_DIR = ''

cfg.MODEL = CN()
cfg.MODEL.FACE_FEATURE_SAVE_PATH = ''
cfg.MODEL.BERT_FEATURE_SAVE_PATH = ''
cfg.MODEL.BACKGROUND_FEATURE_SAVE_PATH = ''
cfg.MODEL.CHARACTER_TO_IDX = ''
cfg.MODEL.IDX_TO_CHARACTER = ''

cfg.MODEL.MAX_EDGES = 
cfg.MODEL.DROPOUT = 
# cfg.MODEL.DROPOUT = 
cfg.MODEL.ADD_NEIGHBOR_FEATURE_RATIO = 
cfg.MODEL.HIDDEN_LAYER_DIM = 
# cfg.MODEL.HIDDEN_LAYER_DIM = 
cfg.MODEL.CLASSIFICATION_HIDDEN_DIM = 
# cfg.MODEL.CLASSIFICATION_HIDDEN_DIM = 
cfg.MODEL.TRANSFORMER_FEED_FORWARD_HIDDEN = 
# cfg.MODEL.TRANSFORMER_FEED_FORWARD_HIDDEN = 
cfg.MODEL.NEW_NODE_FEATURE_WEIGHT = 
cfg.MODEL.TEXT_FEATURE_WEIGHT = 
cfg.MODEL.BACKGROUND_FEATURE_WEIGHT = 
cfg.MODEL.GCAT_OUT_DIM = 
cfg.MODEL.NUM_CLASSES = 10  # begin from 1 to 9, 0 for special annotation
# cfg.MODEL.NUM_CLASSES = 7  # begin from 1 to 6, 0 for special annotation
cfg.MODEL.TRANSFORMER_MEMORY_SIZE = 8

cfg.MODEL.LVU_FACE_FEATURE_SAVE_PATH = ''
cfg.MODEL.LVU_BERT_FEATURE_SAVE_PATH = ''
cfg.MODEL.LVU_BACKGROUND_FEATURE_SAVE_PATH = ''
cfg.MODEL.LVU_CHARACTER_TO_IDX = ''
cfg.MODEL.LVU_IDX_TO_CHARACTER = ''
cfg.MODEL.LVU_VIDEO_SCENE_NAME_PATH = ''

cfg.MODEL.VISR_FACE_FEATURE_SAVE_PATH = ''
cfg.MODEL.VISR_BERT_FEATURE_SAVE_PATH = ''
cfg.MODEL.VISR_BACKGROUND_FEATURE_SAVE_PATH = ''
cfg.MODEL.VISR_CHARACTER_TO_IDX = ''
cfg.MODEL.VISR_IDX_TO_CHARACTER = ''
cfg.MODEL.VISR_VIDEO_SCENE_NAME_TRAIN_PATH = ''
cfg.MODEL.VISR_VIDEO_SCENE_NAME_TEST_PATH = ''

cfg.MODEL.HLVU_FACE_FEATURE_SAVE_PATH = ''
cfg.MODEL.HLVU_BERT_FEATURE_SAVE_PATH = ''
cfg.MODEL.HLVU_BACKGROUND_FEATURE_SAVE_PATH = ''
cfg.MODEL.HLVU_VIDEO_SCENE_NAME_TRAIN_PATH = ''
cfg.MODEL.HLVU_VIDEO_SCENE_NAME_TEST_PATH = ''
